# Generated by Django 4.2 on 2023-05-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_city_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
